steps:
  - label: ":java: mdm"
    command: ./.buildkite/build.sh
    agents:
      queue: maven
      dind: true
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: -1
          limit: 2
        - exit_status: 255
          limit: 1
